CREATE DATABASE Mexant;
USE Mexant;

CREATE TABLE Project
(
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
    MinBudget VARCHAR(20) NOT NULL,
    MaxBudget VARCHAR(20) NOT NULL,
    Date DATETIME,
    Client VARCHAR(40)
);

CREATE TABLE Contact
(
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Message VARCHAR(2000) NOT NULL,
    Phone VARCHAR(30),
    Subject VARCHAR(100)
);

CREATE TABLE Service
(
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(40) NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    Image VARCHAR(200),
    Logo VARCHAR(200)
);

CREATE TABLE GetPlan
(
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(40),
    Email VARCHAR(100),
    Subject VARCHAR(100),
    Reason VARCHAR(40)
);

CREATE TABLE Review
(
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Role VARCHAR(40),
    Description VARCHAR(2000) NOT NULL,
    Image VARCHAR(200)
);